import { prisma } from "@/lib/prisma";
import { createGameSlug } from "@/lib/slugify";
import { requireDeveloper } from "@/lib/auth";
import { getWorkflowTemplate, createWorkflowNodes } from "@/lib/workflow/templates";

function pickTemplate(prompt: string) {
  const p = prompt.toLowerCase();
  if (p.includes("tower") || p.includes("defense")) return "canvas-tower-defense";
  if (p.includes("card")) return "canvas-card-battle";
  if (p.includes("platform") || p.includes("jump")) return "canvas-platformer";
  if (p.includes("space") || p.includes("ship")) return "webgl-space";
  if (p.includes("fight") || p.includes("boss") || p.includes("arena")) return "webgl-arena";
  if (p.includes("run")) return "canvas-runner";
  return "canvas-dungeon";
}

function titleFromPrompt(prompt: string) {
  const cleaned = prompt.replace(/[^a-zA-Z0-9\s]/g, " ").trim();
  const words = cleaned.split(/\s+/).filter(Boolean).slice(0, 5);
  if (words.length > 0) return words.map((word) => word[0]?.toUpperCase() + word.slice(1)).join(" ");
  return "AI Sandbox Prototype";
}

function configFromPrompt(prompt: string, template: string) {
  const p = prompt.toLowerCase();
  const theme = p.includes("cyber") ? "Cyberpunk neon city" : p.includes("space") ? "Deep space battlefield" : p.includes("fantasy") ? "Fantasy adventure realm" : p.includes("volcano") ? "Volcano arena" : "AI generated arcade world";
  return {
    template,
    theme,
    objective: p.includes("boss") ? "Defeat the boss and survive enemy waves." : "Collect points, defeat enemies, and survive as long as possible.",
    playerName: "Hero",
    enemyName: p.includes("robot") ? "Robot Drone" : p.includes("alien") ? "Alien Raider" : "Shadow Enemy",
    bossName: p.includes("dragon") ? "Frost Dragon" : p.includes("overlord") ? "AI Overlord" : "Final Boss",
    items: ["coin", "shield", "energy orb"],
    enemies: ["fast enemy", "heavy enemy", "ranged enemy"],
    difficulty: p.includes("hard") ? "hard" : "medium",
    primaryColor: p.includes("fire") || p.includes("volcano") ? "#fb7185" : "#22d3ee",
    secondaryColor: p.includes("magic") || p.includes("fantasy") ? "#a78bfa" : "#facc15",
    prompt,
  };
}

export async function runWorkflow(input: { templateId: string; prompt: string; publish?: boolean }) {
  const developer = await requireDeveloper();
  const workflowTemplate = getWorkflowTemplate(input.templateId);
  const runtimeTemplate = pickTemplate(input.prompt);
  const title = titleFromPrompt(input.prompt);
  const gameConfig = configFromPrompt(input.prompt, runtimeTemplate);
  const nodes = createWorkflowNodes(input.templateId, input.prompt).map((node) => ({
    ...node,
    status: "complete",
    output:
      node.type === "runtime"
        ? runtimeTemplate
        : node.type === "ai"
          ? `Generated ${node.label.toLowerCase()} from prompt.`
          : node.output || `Completed ${node.label}.`,
  }));

  const workflow = await prisma.workflow.create({
    data: {
      name: `${workflowTemplate.name}: ${title}`,
      description: workflowTemplate.description,
      template: workflowTemplate.id,
      nodes,
      edges: [],
      ownerId: developer.id,
      isPublic: false,
    },
  });

  let slug = createGameSlug(title);
  while (await prisma.game.findUnique({ where: { slug } })) {
    slug = createGameSlug(title);
  }

  const game = await prisma.game.create({
    data: {
      title,
      slug,
      category: runtimeTemplate.includes("webgl") ? "WebGL Prototype" : "Canvas Prototype",
      shortDescription: `Generated by the ${workflowTemplate.name} workflow.`,
      description: input.prompt,
      tags: ["AI Game", "Workflow", runtimeTemplate, "HTML5"],
      screenshots: [],
      coverImage: "https://placehold.co/1200x630/png",
      playUrl: `/play/${slug}`,
      gameTemplate: runtimeTemplate,
      gameConfig,
      seoTitle: `Play ${title} Online`,
      promoLine: "Generated through an AI game workflow studio.",
      imagePrompt: `${title} game cover art, ${gameConfig.theme}, high contrast, modern indie game poster`,
      aiQualityScore: 78,
      aiQualitySummary: "Workflow-generated playable prototype ready for sandbox editing and feedback.",
      aiSeoChecklist: ["Clear genre", "Playable link", "Tags", "Share copy", "Feedback loop"],
      aiImprovementTips: ["Add custom cover art", "Tune difficulty", "Test score balance"],
      aiPublishPack: {
        x: `I generated ${title}, a playable AI game prototype, from a workflow studio.`,
        reddit: `I built a playable HTML5/WebGL prototype called ${title}. Feedback welcome.`,
        embed: `<iframe src=\"/play/${slug}\" width=\"960\" height=\"540\"></iframe>`,
      },
      status: "PENDING",
      developerId: developer.id,
    },
  });

  await prisma.gameVersion.create({
    data: {
      gameId: game.id,
      versionNumber: 1,
      changePrompt: `Initial workflow run: ${input.prompt}`,
      configSnapshot: gameConfig,
      titleSnapshot: title,
    },
  });

  const workflowRun = await prisma.workflowRun.create({
    data: {
      workflowId: workflow.id,
      prompt: input.prompt,
      status: "complete",
      logs: nodes.map((node) => `${node.order}. ${node.label}: complete`),
      output: { gameId: game.id, slug: game.slug, template: runtimeTemplate, workflowId: workflow.id },
      gameId: game.id,
    },
  });

  return { workflow, workflowRun, game };
}
